id = "hexa"
name = "Hexa"
description = "Hexa Programming Language"
version = "0.0.1"
schema_version = 1
authors = ["PeyTy"]
repository = "https://github.com/hexalang/hexa-zed-bundle"

[grammars.actionscript]
repository = "https://github.com/Rileran/tree-sitter-actionscript"
commit = "24919034fc78fdf9bedaac6616b6a60af20ab9b5"
